# Generated by Django 4.1 on 2022-09-26 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('course_slug', models.CharField(max_length=50)),
                ('period', models.IntegerField()),
                ('start', models.DateField()),
                ('coordinator', models.CharField(max_length=50)),
                ('max_student_per_period', models.IntegerField()),
                ('accept_new_inscriptions', models.BooleanField()),
            ],
        ),
    ]
