# Generated by Django 4.1 on 2022-09-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='max_student_per_period',
            new_name='max_students_per_period',
        ),
    ]
