# Generated by Django 4.1 on 2022-09-29 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='total_hour',
            new_name='total_hours',
        ),
    ]
